### PR TITLE
WIP Custom Viewers Initial Setup

### PR DESCRIPTION
**Pull request by ikreymer**
This setup adds a PDF and EPUB viewers, and a couple of test cases, under the `reading-room` collection.
The system uses the existing content-type filtering, and also adds extension filtering for epubs, as they often do not have a custom mime type.

The sample data includes the following URLs:

- `http://localhost:8080/reading-room/http://www.africau.edu/images/default/sample.pdf` - simple PDF test that loads in a custom viewer.

- `http://localhost:8080/reading-room/https://idpf.github.io/epub3-samples/30/samples.html` an HTML page which links to multiple EPUBs, which normally would just download, but should open in the EPUB viewer.

This also uses a new branch of pywb that adds an `ir_` modifier, that supports unrewritten content but with `Location` headers still being rewritten to simplify loading unrewritten content.

To Do

- [x] Update the Terms, including translations as appropriate.
- [x] Make sure the Terms only show up when configured to do so, because that's only for the reading room.

### CODE REVIEW

**Comment by ikreymer** [comment]
Currently, this PR modifies the existing `reading-room` collection, but can make a copy of that if the config is needed for something else.

**Comment by anjackson** [comment]
No, it's fine to use the `reading-room` collection - this is what it's for.

Aside: Did you ever look at integrating Ruffle for Flash playback? I seem to remember you did, but can't find a reference... Ah, is it the JS implementation!? ... Ah, [yes it is](https://github.com/webrecorder/replayweb.page/blob/178d0507eb08e838334a2919e2822692ef275208/src/sw.js#L20) --- I've vaguely struck by the similarity of what we're doing with some of the aims of the Universal Viewer project, and whether long term we should look at a more generic JavaScript-based playback system supporting a growing range of formats through some modular means...

**Comment by anjackson** [comment]
Some issues I'm having, in https://github.com/ukwa/ukwa-pywb/issues/92

**Comment by anjackson** [comment]
Note that I've merged these changes into #101 as I want to do one big round of testing.  Will leave this PR open for now.

**Comment by anjackson** [comment]
I've changed my mind. We need to proceed with this separate from the 2.7 Vue timeline changes. So I've brought @tw4l latest updates into this PR and will merge it and mint a `2.6.9-LDA-1` version. This will probably involve back-porting some changes from the `2.7.x` branch.

**Comment by anjackson** [comment]
This has been updated to include more recent changes, and backporting updates to the terms pages.

**Comment by anjackson** [comment]
There a still a few translation gaps, but hanging on to this PR for so long is causing problems, so I'm merging

**Pull request merged**
